# Generated by Django 3.0.2 on 2020-01-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_auto_20200122_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
